### ISSUE TITLE
MissingOutputException in rule FrEIA_score

### ISSUE THREAD

**Issue by LaerkeRosenlund** [mouliere-lab/FrEIA#3]
Hi mouliere-lab,
I am trying to run your FrEIA score calculation with your Dummy Data Set and your guide to run on a local machine using Snakemake. It has progressed well until step 4 "Calculate fragment end proportions and the FrEIA score". I get the attached error code every time and I've tried setting up --latency-wait. Do you have any idea what I'm doing wrong?

Kind regards Lærke

![fejlkode1](https://user-images.githubusercontent.com/117812895/207805949-d35c9796-e58b-4cf2-84ce-a76e80febcac.png)

**Comment by moldovannorbert** [comment]
Dear @LaerkeRosenlund , 
Thanks for your feedback and patients.

If this is still an issue for you, can you please post the content of the log file from /logs/<ProjectName>/4_FrEIA/5_FrEIA_score/FrEIA_score.log?

**Comment by moldovannorbert** [comment]
Dear @Jirachi-385,

Thank you for confirming this issue. I managed to replicate this bug on my machine and fixed it. Can you please clone my updates and report back?

Best,
Norbert

**Comment by ghost** [comment]
@moldovannorbert
Thank you for your quick response.
The tool you fixed worked well!

**Comment by moldovannorbert** [comment]
@Jirachi-385 thanks for your feedback!
